language: generic

branches:
  only:
  - master

sudo: required

services:
  - docker

before_script:
  - docker -v
  - docker-compose -v
  - sudo service mysql stop
  - docker-compose build
  - docker-compose up -d
  - docker ps -a
  - sleep 30

script:
  - curl http://localhost:3030

after_script:
  - docker-compose -f docker-compose.travis.yml down