language: generic

branches:
  only:
  - master

sudo: required

services:
- docker

before_script:
- docker -v
- docker-compose -v
- sudo service mysql stop
- docker-compose build
- docker-compose up -d
# - sleep 30

script:
# - curl http://localhost:3030

after_script:
- docker-compose -f docker-compose.travis.yml down

before_install:
- openssl aes-256-cbc -K $encrypted_da2751d119bb_key -iv $encrypted_da2751d119bb_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 400 ~/.ssh/id_rsa
- eval "$(ssh-agent -s)"
- ssh-add ~/.ssh/id_rsa
- ssh newuser@54.169.86.114 pwd


# before_deploy:
#   - eval "$(ssh-agent -s)"
#   - ssh-add ~/.ssh/id_rsa
#   - ssh newuser@54.169.86.114
#   - cd /home/work/reddit_with_snack/
#   - sudo git pull origin master

# deploy:
#   provider: script
#   skip_cleanup: true
#   script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/<dir> <ssh-user>@<deploy-host>:path/to/files
#   on:
#     branch: master